version: '3'

services:
  myapp:
    build: .
    container_name: "Demo_app"
    command: python manage.py runserver 0.0.0.0.8000
    ports:
    - '8001:8000'
  db_postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    restart: unless-stopped
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ~/data:/var/lib/data
    
